name: CI-Delivery

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Kiuwan Delivery Action
      uses: lsacera/KiuwanBaselineAction@v0.4
      id: kstep
      with:
        project: Personalblog
        label: ${{ github.run_number }}
        userid: ${{ secrets.KIUWAN_USER }}
        password: ${{ secrets.KIUWAN_PASS }}
        changerequest: cr_test
        branch: $${{ github.ref }}
      
    - name: show results step
      run: echo 'The result was ${{ steps.kstep.outputs.result }} and the message was ${{ steps.kstep.outputs.message }} and the audit result ${{ steps.kstep.outputs.auditresult }} and The url was ${{ steps.kstep.outputs.analysisurl }}.'
      
